import { Bot, Database, Shield, Cpu, Zap } from "lucide-react";

export default function SettingsPage() {
  return (
    <div className="h-[calc(100vh-7rem)] overflow-y-auto">
      <div className="max-w-2xl mx-auto px-6 py-10">
        {/* Header */}
        <div className="mb-10">
          <div className="badge mb-4">
            <Zap className="w-3 h-3" />
            Read-only · Configuration overview
          </div>
          <h1 className="text-3xl font-bold mb-2">Settings</h1>
          <p className="text-gray-500 text-sm">Agent configuration and data source details.</p>
        </div>

        <Section title="AI Agent" icon={Bot}>
          <ConfigItem
            label="Language Model"
            value="gemini-3.1-flash-lite"
            description="Used for intent classification, AQL generation, and answer synthesis."
            status="active"
          />
          <ConfigItem
            label="Context Window"
            value="10 turns"
            description="CloudMind remembers the last 10 Q&A pairs per session via Redis."
          />
          <ConfigItem
            label="Query Limit"
            value="100 resources"
            description="Maximum resources returned per ArangoDB query."
          />
          <ConfigItem
            label="Response Timeout"
            value="20 seconds"
            description="Hard timeout per request before showing a retry prompt."
          />
        </Section>

        <Section title="Data Source" icon={Database}>
          <ConfigItem
            label="Discovery Tool"
            value="FixInventory + Floci"
            description="Cloud metadata populated by FixInventory scanning a local Floci environment."
            status="active"
          />
          <ConfigItem
            label="Graph Database"
            value="ArangoDB"
            description="Resources and relationships stored as vertices and edges. 16 nodes · 10 edges."
            status="active"
          />
          <ConfigItem
            label="Session Cache"
            value="Redis"
            description="Conversation context stored in Redis with a 24-hour TTL."
            status="active"
          />
        </Section>

        <Section title="Authentication" icon={Shield}>
          <ConfigItem
            label="Auth Method"
            value="Cookie session"
            description="HTTP-only cookie — no external auth provider, no Clerk, no OAuth."
          />
          <ConfigItem
            label="Session Duration"
            value="7 days"
            description="Sessions expire after 7 days. Signing out clears the cookie immediately."
          />
        </Section>

        <Section title="Stack" icon={Cpu}>
          <ConfigItem label="Frontend" value="Next.js 14" description="App Router · React Server Components · Tailwind CSS." />
          <ConfigItem label="Backend" value="FastAPI" description="Python async API with StreamingResponse for token-by-token chat." />
          <ConfigItem label="Graph Query" value="AQL (ArangoDB Query Language)" description="Auto-generated by Gemini from natural language." />
        </Section>
      </div>
    </div>
  );
}

function Section({
  title,
  icon: Icon,
  children,
}: {
  title: string;
  icon: React.ElementType;
  children: React.ReactNode;
}) {
  return (
    <section className="mb-6">
      <div className="flex items-center gap-2 mb-3">
        <Icon className="w-3.5 h-3.5 text-gray-500" />
        <h2 className="text-xs font-medium text-gray-500 uppercase tracking-wider">{title}</h2>
      </div>
      <div className="card-glass overflow-hidden divide-y divide-white/[0.05]">{children}</div>
    </section>
  );
}

function ConfigItem({
  label,
  value,
  description,
  status,
}: {
  label: string;
  value: string;
  description: string;
  status?: "active";
}) {
  return (
    <div className="flex items-start justify-between gap-4 px-5 py-4">
      <div className="min-w-0">
        <p className="text-sm font-medium text-gray-200">{label}</p>
        <p className="text-xs text-gray-600 mt-0.5 leading-relaxed">{description}</p>
      </div>
      <div className="flex items-center gap-2 shrink-0 mt-0.5">
        {status === "active" && (
          <div className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse" />
        )}
        <span className="text-xs font-mono bg-white/[0.05] border border-white/[0.08] px-2.5 py-1 rounded-lg text-gray-300">
          {value}
        </span>
      </div>
    </div>
  );
}
